### ISSUE TITLE
how to sequence effects with flare UI?

### ISSUE THREAD

**Issue by joelgrus** [sharkdp/purescript-flare#14] opened 2016-03-22 17:23 UTC
Say I would like a slider to choose a number `n` and then plot `n` random points.

I can do this easily if the points are deterministic, but once they're random I need to generate them in an `Eff (random :: RANDOM | e)` context, and it's not obvious to me how to sequence that with the UI applicative. (I tried a number of things, but none of them worked.)

See example (and non-example): https://gist.github.com/joelgrus/b27c12fc159367ea2440

I hope this is the right venue to ask this kind of question. Thanks!

**Comment by sharkdp** [comment] 2016-03-22 18:52
> I hope this is the right venue to ask this kind of question.

Sure!

As you pointed out, the issue is that `runFlareDrawing` expects a `UI Drawing`, i.e. some interface that produces a _pure_ value (a `Drawing`). As you have to run an effectful computation to generate that `Drawing`, you cannot use `runFlareDrawing`.

You can solve this by using `runFlareWith` instead (in your case, `a = Int`):

``` purs
runFlareWith :: forall e. ElementId
             -> (a -> Eff (dom :: DOM, channel :: CHANNEL | e) Unit)
             -> UI e a
             -> Eff (dom :: DOM, channel :: CHANNEL | e) Unit
```

As the second argument, this expects a custom function that can run any effectful computation (for you, `eff` includes `RANDOM` and `Canvas`). You can provide your own rendering function, something like:

``` purs
drawRandomPoints :: forall eff. Context2D
                 -> Int
                 -> Eff (random :: RANDOM, canvas :: Canvas | eff) Unit
drawRandomPoints ctx n = do
  clearRect ctx { x: 0.0, y: 0.0, w: width, h: height }

  drawing <- randomPoints n
  render ctx drawing
```

Finally, in your main function, you would call `runFlareWith` instead:

``` purs
main = do
  Just canvas <- getCanvasElementById "canvas"
  ctx <- getContext2D canvas

  let ui = intRange "numPoints" 1 100 10

  runFlareWith "controls" (drawRandomPoints ctx) ui
```

You can try it out here: http://sharkdp.github.io/try-flare/?gist=bdb4548abb6103be3e2a

**Comment by sharkdp** [comment] 2016-05-08 12:37
@joelgrus 
Can this be closed?

**Comment by oblitum** [comment] 2016-06-16 03:37
Question and answer were very helpful.

**Comment by oblitum** [comment] 2016-06-17 08:43
An updated sample for this using latest purescript would be nice to have.

**Comment by oblitum** [comment] 2016-06-17 15:35
I've added it as example 17 in this gist: https://gist.github.com/oblitum/90cbf5338f55321a9d975f0588a711cd

**Comment by oblitum** [comment] 2016-06-21 10:09
I've finished a more complete sample which I [incorporated in a blog post](http://nosubstance.me/post/nature-invented-it-first/), it's still small:
- source: https://gist.github.com/oblitum/94350d0651a1d91d8c80297f950d399b#file-main-purs
- result: http://bl.ocks.org/oblitum/raw/94350d0651a1d91d8c80297f950d399b/

You may feel free to incorporate it to the repository. Consider it public domain.

Notice that for now this one has moved the random computation outside of the controller, example 17 above is more correct in this aspect. Now... it seems I got back to this issue. How can I get the reset button to always reset the random points to a **new** initial random state instead of a static one... (since I'm managing `model`'s state through usage of `foldp`, which is UI code, not controller)?

**Comment by oblitum** [comment] 2016-06-23 15:29
I've noticed also that that technique of using `foldp` to start/reset the animation while having an internal `animationFrame` seems to turn framerate quiter slower (running just the `view` instead of the `resetView` is faster). Sadly I dunno how to do the same (having start and reset state) in a different way (not running `animationFrame` internally to a `foldp`).

@sharkdp I'd like to know your judgement regarding this. I'm feeling I'm already hitting the limitations with Flare here (I'm not sure)? I'm just starting in FP again because of PureScript but the way I've done state management of buttons seems a bit contrived, restrictive and resource hungry (`foldp` with `animationFrame`). And I really wished to get back to the state of example 17, with a effectful computation (random) as the controller, while also, having the buttons and animation working like they are currently.

**Comment by sharkdp** [comment] 2016-08-05 19:57
Sorry for the late answer.

> I've finished a more complete sample which I incorporated in a blog post

Very nice!

> You may feel free to incorporate it to the repository. Consider it public domain.

Thanks, I've added a link in the README.

> How can I get the reset button to always reset the random points to a new initial random state instead of a static one...

has this been resolved in the mean time?

**Comment by oblitum** [comment] 2016-08-05 21:02
> has this been resolved in the mean time?

No, I haven't touched the code since then, but I'd be interested in a flare sample of that, I'm still at https://github.com/sharkdp/purescript-flare/issues/14#issuecomment-228087969 state.

Right now I'm trying to finish "PureScript by Example", so in those samples I touched subjects which I was not familiar with. After the book I'd go about studing other libs and flare to check whether I've hit the limit with flare and it would be more natural using pux, or other lib.

**Comment by oblitum** [comment] 2016-08-05 21:10
> Thanks, I've added a link in the README.

Thanks!

**Comment by sharkdp** [comment] 2016-08-07 08:37
> Sadly I dunno how to do the same (having start and reset state) in a different way (not running animationFrame internally to a foldp).

Currently, I cannot think of any other way, either. I was thinking about saving a "reset time" every time you press "reset", but that would also require you to pass the `animationFrame` signal through `foldp`. 

You could probably nest two Flare UIs. The outer one would completely re-start the inner Flare, whenever "reset" is clicked. But ...

> I'm feeling I'm already hitting the limitations with Flare here (I'm not sure)?

Quite possible. I encourage you to try out different PureScript UI frameworks. Flare is really only suited for "spreadsheet-like" UIs and the only way to incorporate "mutable state" is by using `foldp`.

I'm closing this, as the initial issue is resolved, I think. But let me know if you find out something else.

**Closed as completed by sharkdp** 2016-08-07 08:37 UTC
